### ISSUE TITLE
Toggle button text rendering is inconsistent in HTML builds

### ISSUE THREAD

**Issue by doctor-g** [spring-studio-2016/monsters#32]
In the latest build, the text is not shown at all on the toggle buttons in player creation screen, although they show up fine in the Java build.

**Comment by zbruh** [comment]
I think this has something to do with the screen size.  Even zoom affects it. If I bring my window to close to the standard size, it looks fine. If I zoom in (effectively less space) and then refresh, the buttons overflow. If I zoom out, the buttons are really thin.

We might be able to use zooming as a temporary workaround if the devices we're using have high density screens.
