### ISSUE TITLE
Region, skill, and reaction buttons use different cases

### ISSUE THREAD

**Issue by doctor-g** [spring-studio-2016/monsters#59]
They should all use the same case, preferably mixed case (e.g. "North America").

**Comment by zbruh** [comment]
@doctor-g Does this include reactions, too? I believe all-caps reactions was an intentional decision on the part of the writers.

**Comment by doctor-g** [comment]
@zbruh I don't see a good reason for it, though. There's nothing that projects a design decision to the player, so it is perceived as arbitrary (or worse, unprofessional).

**Comment by doctor-g** [comment]
Fixed with #64
