### ISSUE TITLE
Image artifacts around monster hand

### ISSUE THREAD

**Issue by doctor-g** [spring-studio-2016/monsters#60]
In the image, you can see white splotches which are coming from the source image. They should be cleaned up.

![image](https://cloud.githubusercontent.com/assets/6951973/14711293/cd20b760-07a6-11e6-99cd-23e1776c83fe.png)

**Comment by jtmcginnis** [comment]
A consequence of you and I trying to edit the image with MS Paint.

**Comment by zbruh** [comment]
I'm pretty good with Photoshop, I can clean this up.
